---
# file: global.yml

# This play runs first, and gathers a complete set of properties for everything
- hosts: all
  sudo: True
  tasks:
    setup:
      filter: '*'

# - include: play_change_kernel.yml

# This imports provisioner-specific variables. We do this as a block, which makes access 
# more awkward, but does allow us not to worry about other things. 
- hosts: all
  vars_files:
    - 'vars/common.yml'
    - 'vars/external.yml'
    - 'vars/provisioning_platform_{{ provisioning_platform }}.yml'
    - 'vars/provisioning_platform_default.yml'
  sudo: True
  tasks:
    - name: set provisioner facts
      action: set_fact
      args: 
        provisioner_values: "{{ provisioner_values }}"

# Next, let's generate common files, such as the hosts file. This requires the
# previous setup to have been run in a separate play, it seemed
- hosts: all
  vars_files:
    - 'vars/common.yml'
    - 'vars/external.yml'
    - 'vars/provisioning_platform_{{ provisioning_platform }}.yml'
    - 'vars/provisioning_platform_default.yml'
  sudo: True
  roles:
    - { role: common, tags: [ 'common' ] }

- include: play_deploy_shared_storage.yml

- include: play_deploy_grid_engine.yml

- include: play_deploy_tools.yml

- include: play_deploy_data.yml

- include: play_deploy_workflows.yml

- include: play_deploy_database_server.yml

- include: play_deploy_webapp_server.yml

