---
# file: global.yml

# This play runs first, and gathers a complete set of properties for everything
- hosts: all
  sudo: True
  tasks:
    setup:
      filter: '*'

# This imports provisioner-specific variables. We do this as a block, which makes access 
# more awkward, but does allow us not to worry about other things. 
- hosts: all
  sudo: True
  vars_files:
    - [ 'vars/provisioning_platform_{{ provisioning_platform }}.yml', 'vars/provisioning_platform_default.yml']
  tasks:
    - name: set provisioner facts
      action: set_fact
      args: 
        provisioner_values: "{{ provisioner_values }}"

# Next, let's generate common files, such as the hosts file. This requires the
# previous setup to have been run in a separate play, it seemed
- hosts: all
  sudo: True
  roles:
    - role: common

- hosts: grid-master:grid-worker
  sudo: True
  roles:
    - role: java
    - role: storage

# Now create the main storage systems on the master
- hosts: grid-master
  sudo: True
  tasks:
    - include: roles/storage/tasks/create.yml

# Start storage on all nodes
- hosts: grid-master:grid-worker
  sudo: True
  tasks:
    - include: roles/storage/tasks/start.yml

# The grid master depends on the hosts file, as we need to know at least who we
# are by this stage. 
- hosts: grid-master 
  sudo: True
  roles:
    - { role: grid-engine, grid_engine_master: True }

- hosts: grid-worker 
  sudo: True
  roles:
    - { role: grid-engine, grid_engine_master: False }

# Add all the tools that we need for the full pipeline. Order does matter
# here. It's a good plan to build common platforms like perl and python before you
# use them. And use the right ones. 
- hosts: grid-worker 
  sudo: True
  roles:
    - { role: tools, selected_tool: 'r' }
    - { role: tools, selected_tool: 'perl' }
    - { role: tools, selected_tool: 'python27' }
    - { role: tools, selected_tool: 'bam2fastq' }
    - { role: tools, selected_tool: 'bfast' }
    - { role: tools, selected_tool: 'blat' }
    - { role: tools, selected_tool: 'bowtie2' }
    - { role: tools, selected_tool: 'idba' }
    - { role: tools, selected_tool: 'picard' }
    - { role: tools, selected_tool: 'sga' }
    - { role: tools, selected_tool: 'shrimp2' }
    - { role: tools, selected_tool: 'capsid' }

- hosts: database
  sudo: True
  roles:
    - role: database

- hosts: webapp
  sudo: True
  roles:
    - role: java
    - role: webapp

