---
# file: global.yml

# This play runs first, and gathers a complete set of properties for everything
- hosts: all
  sudo: True
  tasks:
    setup:
      filter: '*'

# Next, let's generate common files, such as the hosts file. This requires the
# previous setup to have been run in a separate play, it seemed
- hosts: all
  sudo: True
  roles:
    - role: common

- hosts: grid-master:grid-worker
  sudo: True
  roles:
    - role: java
    - role: perl
    - role: storage

# Now create the main storage systems on the master
- hosts: grid-master
  sudo: True
  tasks:
    - include: roles/storage/tasks/create.yml

# Start storage on all nodes
- hosts: grid-master:grid-worker
  sudo: True
  tasks:
    - include: roles/storage/tasks/start.yml

# The grid master depends on the hosts file, as we need to know at least who we
# are by this stage. 
- hosts: grid-master 
  sudo: True
  roles:
    - { role: grid-engine, grid_engine_master: True }

- hosts: grid-worker 
  sudo: True
  roles:
    - role: pipeline
    - { role: grid-engine, grid_engine_master: False }

- hosts: database
  sudo: True
  roles:
    - role: database

- hosts: webapp
  sudo: True
  roles:
    - role: java
    - role: webapp

