---
# We also need the data download system. This we only need on the master node.
# We also can grab and download the databases. This is also master-consistent, as
# we only want one copy, and written on the shared data drives. Use a similar 
# to the tools, to allow us to break up the components a bit more easily.

- hosts: grid-master 
  sudo: True
  vars_files:
    - 'vars/common.yml'
    - 'vars/external.yml'
    - 'vars/provisioning_platform_{{ provisioning_platform }}.yml'
    - 'vars/provisioning_platform_default.yml'
  roles:
    - { role: data-download, selected_tool: 'parallel' }
    - { role: data-download, selected_tool: 's3cmd' }
    - { role: data-download, selected_tool: 'gene_torrent' }
    - { role: data-download, selected_tool: 'blast' }
