---
- hosts: webapp
  vars_files:
    - 'vars/common.yml'
    - 'vars/external.yml'
    - 'vars/provisioning_platform_{{ provisioning_platform }}.yml'
  sudo: True
  roles:
    - role: java
    - role: webapp

