---
# file: roles/storage/moosefs/tasks/install.yml
# These tasks are run on all nodes
- name: Storage | Install build-essential
  apt: pkg={{ item.package }} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - { package: 'build-essential' }
    - { package: 'pkg-config' }
    - { package: 'libfuse-dev' }
    - { package: 'zlib1g-dev' }

- name: Storage | Create group
  group: name=mfs state=present system=yes

- name: Storage | Create user
  user: name=mfs group=mfs state=present group=mfs system=yes

- name: Storage | Get sources
  get_url:
    dest: "/tmp/mfs-1.6.27-5.tar.gz"
    url: http://sourceforge.net/projects/moosefs/files/moosefs/1.6.27/mfs-1.6.27-5.tar.gz

- name: Storage | Unpack moosefs
  command: tar xf /tmp/mfs-1.6.27-5.tar.gz chdir=/tmp creates=/tmp/mfs-1.6.27

- name: Storage | Configure moosefs
  command: ./configure chdir=/tmp/mfs-1.6.27 creates=/tmp/mfs-1.6.27/config.h

- name: Storage | Build moosefs
  shell: make && make install chdir=/tmp/mfs-1.6.27 creates={{ moosefs.sysconfdir }}
