---
# file: roles/storage/tasks/lustre_install.yml
# These tasks are run on all server nodes
# https://build.hpdd.intel.com/job/lustre-master/arch=x86_64,build_type=client,distro=ubuntu1004,ib_stack=inkernel/

- name: Storage | Install lustre 
  apt: pkg={{ item.package }} state=present
  with_items:
    - { package: 'lustre-utils' }

- include: create_storage_bricks.yml

- name: Storage | Create lustre brick volume
  shell: mkfs.lustre --ost /data/brick1/gv0
  when: storage_action == 'install'

- name: Storage | Start lustre-server
  service: name=lustre-server state=started
  when: storage_action == 'install'
