---
# Ansible tasks required to install bam2fastq. 
- name: bam2fastq | Installing required dependencies
  apt: pkg={{item}} state=present update_cache=yes cache_valid_time=3600
  with_items: 
    - 'build-essential'
    - 'automake'

- name: bam2fastq | Preparing vendor build
  file: 
    path: "{{ vendor_build }}"
    state: directory

- name: bam2fastq | Download bam2fastq
  get_url:
    dest: '{{ vendor_build }}/bam2fastq-{{ bam2fastq_version }}.tgz'
    url: 'http://gsl.hudsonalpha.org/static/software/bam2fastq-{{ bam2fastq_version }}.tgz'

- name: bam2fastq | Uncompress bam2fastq
  shell: tar xfz {{ vendor_build }}/bam2fastq-{{ bam2fastq_version }}.tgz chdir={{ vendor_build }} creates={{ vendor_build }}/bam2fastq-{{ bam2fastq_version }}

- name: bam2fastq | Build bam2fastq
  shell: make chdir={{ vendor_build }}/bam2fastq-{{ bam2fastq_version }} creates={{ vendor_build }}/bam2fastq-{{ bam2fastq_version }}/bam2fastq

- name: bam2fastq | Install bam2fastq
  shell: cp {{ vendor_build }}/bam2fastq-{{ bam2fastq_version }}/bam2fastq {{ vendor_base }}/bin/bam2fastq creates={{ vendor_base }}/bin/bam2fastq
