- name: bfast | Installing required dependencies
  apt: pkg={{item}} state=present update_cache=yes cache_valid_time=3600
  with_items: 
    - 'libbz2-dev'

- name: bfast | Get bfast
  get_url:
    dest: '{{ vendor_build }}/bfast-0.7.0a.tar.gz'
    url: 'http://sourceforge.net/projects/bfast/files/bfast/0.7.0/bfast-0.7.0a.tar.gz/download'

- name: bfast | Unpack bfast
  shell: tar xf {{ vendor_build }}/bfast-0.7.0a.tar.gz chdir={{ vendor_build }} creates={{ vendor_build }}/bfast-0.7.0a

- name: bfast | Configure bfast
  shell: ./configure --prefix={{ vendor_base }} chdir={{ vendor_build }}/bfast-0.7.0a creates={{ vendor_build }}/bfast-0.7.0a/config.h

- name: bfast | Build bfast
  shell: make chdir={{ vendor_build }}/bfast-0.7.0a creates={{ vendor_build }}/bfast-0.7.0a/bfast/bfast

- name: bfast | Install bfast
  shell: make install chdir={{ vendor_build }}/bfast-0.7.0a creates={{ vendor_build }}/bin/bfast
