---
# CaPSID pipeline
- name: CaPSID pipeline | Install development tools
  apt: pkg={{ item.package }} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - { package: 'git' }

- name: CaPSID pipeline | Check out CaPSID from Github
  git:
    repo: https://github.com/capsid/capsid-pipeline.git
    dest: "{{ vendor_base }}/capsid_pipeline"
    update: yes
    version: develop

# OF course, if we had dependencies that were Debian packaged and suitable, then
# that would be better to reduce C compilation time. 

- name: CaPSID pipeline | Install CaPSID dependencies
  shell: "{{ vendor_base }}/bin/pip install -e . chdir={{ vendor_base }}/capsid_pipeline"

# There is no good reason why we ought to need to do this, but we might. Anyway,
# here we go. 

- name: CaPSID pipeline | Install CaPSID
  shell: "{{ vendor_base }}/bin/python setup.py install chdir={{ vendor_base }}/capsid_pipeline"

