---

# Ansible tasks required to install Jared Simpson's SGA aligner. This is taken from
# Github and installed more or less as indicated through the README.md file. 

- name: SGA | Installing required dependencies
  apt: pkg={{item}} state=present update_cache=yes cache_valid_time=3600
  with_items: 
    - 'build-essential'
    - 'zlib1g-dev'
    - 'libjemalloc-dev'
    - 'git'
    - 'cmake'
    - 'automake'

- name: SGA | Download sparsehash
  get_url:
    dest: '{{ vendor_build }}/sparsehash-{{ sparsehash_version }}.tar.gz'
    url: 'https://sparsehash.googlecode.com/files/sparsehash-{{ sparsehash_version }}.tar.gz'

- name: SGA | Uncompress sparsehash
  shell: tar xfz {{ vendor_build }}/sparsehash-{{ sparsehash_version }}.tar.gz chdir={{ vendor_build }} creates={{ vendor_build }}/sparsehash-{{ sparsehash_version }}

- name: SGA | Configure sparsehash
  shell: ./configure --prefix={{ vendor_base }} chdir={{ vendor_build }}/sparsehash-{{ sparsehash_version }} creates={{ vendor_build }}/sparsehash-{{ sparsehash_version }}/Makefile

- name: SGA | Build sparsehash
  shell: make chdir={{ vendor_build }}/sparsehash-{{ sparsehash_version }} creates={{ vendor_build }}/sparsehash-{{ sparsehash_version }}/libsparsehash.pc

- name: SGA | Install sparsehash
  shell: make install chdir={{ vendor_build }}/sparsehash-{{ sparsehash_version }} creates={{ vendor_base }}/include/sparsehash

- name: SGA | Check out bamtools from Github
  git:
    repo: git://github.com/pezmaster31/bamtools.git
    dest: "{{ vendor_build }}/bamtools"
    update: yes
    version: master

- name: SGA | Create a build directory
  shell: mkdir -p build chdir={{ vendor_build }}/bamtools creates={{ vendor_build }}/bamtools/build

- name: SGA | Build bamtools
  shell: "{{item.command}} chdir={{item.directory}} creates={{item.creates}}"
  with_items: 
    - { command: "cmake ..", directory: "{{ vendor_build }}/bamtools/build", creates: "{{ vendor_build }}/bamtools/build/Makefile" }
    - { command: "make", directory: "{{ vendor_build }}/bamtools/build", creates: "{{ vendor_build }}/bamtools/bin/bamtools" }
    - { command: "make install", directory: "{{ vendor_build }}/bamtools/build", creates: "{{ vendor_base }}/bin/bamtools" }

- name: SGA | Install python modules
  shell: "{{ vendor_base }}/bin/pip install {{item.module}} creates={{item.creates}}"
  with_items: 
    - { module: "pysam", creates: "{{ vendor_base }}/lib/python2.7/site-packages/pysam" }
    - { module: "ruffus", creates: "{{ vendor_base }}/lib/python2.7/site-packages/ruffus" }

- name: SGA | Check out SGA from Github
  git:
    repo: https://github.com/jts/sga.git
    dest: "{{ vendor_build }}/sga"
    update: yes
    version: master

- name: SGA | Prepare to configure SGA
  shell: ./autogen.sh chdir={{ vendor_build }}/sga/src creates={{ vendor_build }}/sga/src/configure

- name: SGA | Configure SGA
  shell: ./configure --prefix={{ vendor_base }} --with-bamtools={{ vendor_build }}/bamtools chdir={{ vendor_build }}/sga/src creates={{ vendor_build }}/sga/src/config.h

- name: SGA | Build SGA
  shell: make chdir={{ vendor_build }}/sga/src creates={{ vendor_build }}/sga/bin/sga-align

- name: SGA | Install SGA
  shell: make install chdir={{ vendor_build }}/sga/src creates={{ vendor_base }}/bin/sga

