---
# roles/data-download/tasks/blast.yml

- name: Data download | Make data directory
  shell: mkdir -p {{item}} creates={{item}}
  with_items:
    - '{{ vendor_data }}/blast'

# Downloading the Blast database, which is likely split into multiple files
# We want both the original files and digests, just in case.
# Note that we use rsync instead of ftp, because we're not crazy

- name: Data download | Downloading Blast database
  shell: rsync -av --contimeout=300 ftp.ncbi.nlm.nih.gov::blast/db/n[tr].*.tar.gz* {{ vendor_data }}/blast/
  async: 7200
  poll: 60

- name: Data download | Getting downloaded nr*.tar.gz files
  shell: ls nr*.tar.gz chdir={{ vendor_data }}/blast
  register: data_download_blast_nr_files

- name: Data download | Uncompressing Blast database files
  shell: tar xfz {{ item }} chdir={{ vendor_data }}/blast creates={{ vendor_data }}/blast/{{ item |replace(".tar.gz", ".phi") }}
  with_items: data_download_blast_nr_files.stdout_lines

- name: Data download | Getting downloaded nt*.tar.gz files
  shell: ls nt*.tar.gz chdir={{ vendor_data }}/blast
  register: data_download_blast_nt_files

- name: Data download | Uncompressing Blast database files
  shell: tar xfz {{ item }} chdir={{ vendor_data }}/blast creates={{ vendor_data }}/blast/{{ item |replace(".tar.gz", ".nni") }}
  with_items: data_download_blast_nt_files.stdout_lines
