---
# file: roles/storage/tasks/main.yml

# Installation component tasks follow
- include: "{{ storage_system }}_install.yml"
  when: storage_action == 'install'

# Start component tasks follow
- include: "{{ storage_system }}_start.yml"
  when: storage_action == 'start'

# Mount component tasks follow
- include: "{{ storage_system }}_mount.yml"
  when: storage_action == 'mount'
