---
# file: roles/storage/tasks/main.yml

# Installation component tasks follow
- include: glusterfs_install.yml
  when: storage_system == 'glusterfs' and storage_action == 'install'

# Start component tasks follow
- include: glusterfs_start.yml
  when: storage_system == 'glusterfs' and storage_action == 'start'

# Mount component tasks follow
- include: glusterfs_mount.yml
  when: storage_system == 'glusterfs' and storage_action == 'mount'
